name: Constant Velocity Acquisition
view: Tab # Tab or Popup if has an GUI

acquisition_modes: 
  - name: Constant Velocity
    file_name: constant_velocity_acquisition.py

###################################################################
# how to add plugin device in the .navigate/configuration.yaml file
#
# plugin_device:
#   hardware:
#     type: PluginDevice
###################################################################